### ISSUE TITLE
在 GitHub Workflow 多次运行不成功

### ISSUE THREAD

**Issue by liangcun8** [LeeYouRan/linux.do-bot#2]
都是登录失败
![image](https://github.com/user-attachments/assets/5338a622-5c6c-4309-9844-b7b56720b5e4)

**Comment by LeeYouRan** [comment]
确定环境变量里配置的账号和密码是正确的吗？

**Comment by liangcun8** [comment]
环境变量是正常的跑了几天，今天看日志才发现，有几次登录失败，使用服务器跑又是正常的

**Comment by LeeYouRan** [comment]
我看了你github workflow上全部的运行日志，除了第一次跑成功了，其余的都失败了。从时间上就能看出来，其他的时间都太短了。
你第一次运行后有没有改过什么，github workflow上的密钥变量都是大写，你账号有没有直接在浏览器登录过，能正常登录吗。
![image](https://github.com/user-attachments/assets/b9ce20f5-5eb0-428c-b620-f3a273750166)

**Comment by liangcun8** [comment]
测试重新填写变量，可以登录，正常运行。
